package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int idAccount;
     private String username;
     private String password;
     private String type;
     private Set librarians = new HashSet(0);

    public Account() {
    }

	
    public Account(int idAccount, String username, String password, String type) {
        this.idAccount = idAccount;
        this.username = username;
        this.password = password;
        this.type = type;
    }
    public Account(int idAccount, String username, String password, String type, Set librarians) {
       this.idAccount = idAccount;
       this.username = username;
       this.password = password;
       this.type = type;
       this.librarians = librarians;
    }
   
    public int getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(int idAccount) {
        this.idAccount = idAccount;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getLibrarians() {
        return this.librarians;
    }
    
    public void setLibrarians(Set librarians) {
        this.librarians = librarians;
    }

    public void copyAccount(Account iAccount) {
       this.idAccount = iAccount.idAccount;
       this.username = iAccount.username;
       this.password = iAccount.password;
       this.type = iAccount.type;
       this.librarians = iAccount.librarians;
    }
    
    //Hash password by MD5
    //Reference: https://www.geeksforgeeks.org/md5-hash-in-java/
    public String getMD5Hash(String password){
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(password.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashPassword = no.toString(16);
            while (hashPassword.length() < 32) {
                hashPassword = "0" + hashPassword;
            }
            return hashPassword;
        } catch (Exception e) {
            return null;
        }
    }
    //Check password
    public boolean checkPassword(String passString){
        String hashPass = getMD5Hash(passString);
        if(hashPass.compareTo(password) == 0){
            return true;
        }
        else {
            return false;
        }
    }
    


}


