package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BookTitle generated by hbm2java
 */
public class BookTitle  implements java.io.Serializable {


     private Integer idBookTitle;
     private String name;
     private String author;
     private String genre;
     private String publisher;
     private String publishedYear;
     private int price;
     private int numberOfPages;
     private int amount;
     private Date createdDate;
     private Set books = new HashSet(0);

    public BookTitle() {
    }

	
    public BookTitle(String name, String author, String genre, String publisher, String publishedYear, int price, int numberOfPages, int amount, Date createdDate) {
        this.name = name;
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.publishedYear = publishedYear;
        this.price = price;
        this.numberOfPages = numberOfPages;
        this.amount = amount;
        this.createdDate = createdDate;
    }
    public BookTitle(String name, String author, String genre, String publisher, String publishedYear, int price, int numberOfPages, int amount, Date createdDate, Set books) {
       this.name = name;
       this.author = author;
       this.genre = genre;
       this.publisher = publisher;
       this.publishedYear = publishedYear;
       this.price = price;
       this.numberOfPages = numberOfPages;
       this.amount = amount;
       this.createdDate = createdDate;
       this.books = books;
    }
   
    public Integer getIdBookTitle() {
        return this.idBookTitle;
    }
    
    public void setIdBookTitle(Integer idBookTitle) {
        this.idBookTitle = idBookTitle;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public String getPublishedYear() {
        return this.publishedYear;
    }
    
    public void setPublishedYear(String publishedYear) {
        this.publishedYear = publishedYear;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getNumberOfPages() {
        return this.numberOfPages;
    }
    
    public void setNumberOfPages(int numberOfPages) {
        this.numberOfPages = numberOfPages;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


