package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * BorrowedBook generated by hbm2java
 */
public class BorrowedBook  implements java.io.Serializable {


     private BorrowedBookId id;
     private Book book;
     private Reader reader;
     private Date expiredDate;
     private byte isReturn;

    public BorrowedBook() {
    }

    public BorrowedBook(BorrowedBookId id, Book book, Reader reader, Date expiredDate, byte isReturn) {
       this.id = id;
       this.book = book;
       this.reader = reader;
       this.expiredDate = expiredDate;
       this.isReturn = isReturn;
    }
   
    public BorrowedBookId getId() {
        return this.id;
    }
    
    public void setId(BorrowedBookId id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Reader getReader() {
        return this.reader;
    }
    
    public void setReader(Reader reader) {
        this.reader = reader;
    }
    public Date getExpiredDate() {
        return this.expiredDate;
    }
    
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }
    public byte getIsReturn() {
        return this.isReturn;
    }
    
    public void setIsReturn(byte isReturn) {
        this.isReturn = isReturn;
    }

//Format date to String "dd/MM/yyyy"
    public String getStrExpiredDate(){
        SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            return dFormat.format(expiredDate);
        } catch (Exception e) {
            return null;
        }
    }
// Check: Borrowed Book is over due
    public boolean isOverDue(){
        Date today = new Date();
        if(today.compareTo(expiredDate) > 0){
            return true;
        }
        return false;
    }

//calculate days over due
    public long DateDiff(){
       
        DateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date currentDate = new Date();
        Date date1 = null;
        Date date2 = null;
        try {
            String startDate = simpleDateFormat.format(expiredDate);
            String endDate = simpleDateFormat.format(currentDate);

            date1 = simpleDateFormat.parse(startDate);
            date2 = simpleDateFormat.parse(endDate);

            long getDiff = currentDate.getTime() - date1.getTime();

            long getDaysDiff = getDiff / (24 * 60 * 60 * 1000);
             System.out.println(getDaysDiff);
            return getDaysDiff;           
        } catch (Exception e) {
        }
        return 0;
    }
}


