package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BorrowedBookId generated by hbm2java
 */
public class BorrowedBookId  implements java.io.Serializable {


     private int idReader;
     private int idBook;
     private Date borrowedDate;

    public BorrowedBookId() {
    }

    public BorrowedBookId(int idReader, int idBook, Date borrowedDate) {
       this.idReader = idReader;
       this.idBook = idBook;
       this.borrowedDate = borrowedDate;
    }
   
    public int getIdReader() {
        return this.idReader;
    }
    
    public void setIdReader(int idReader) {
        this.idReader = idReader;
    }
    public int getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }
    public Date getBorrowedDate() {
        return this.borrowedDate;
    }
    
    public void setBorrowedDate(Date borrowedDate) {
        this.borrowedDate = borrowedDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BorrowedBookId) ) return false;
		 BorrowedBookId castOther = ( BorrowedBookId ) other; 
         
		 return (this.getIdReader()==castOther.getIdReader())
 && (this.getIdBook()==castOther.getIdBook())
 && ( (this.getBorrowedDate()==castOther.getBorrowedDate()) || ( this.getBorrowedDate()!=null && castOther.getBorrowedDate()!=null && this.getBorrowedDate().equals(castOther.getBorrowedDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdReader();
         result = 37 * result + this.getIdBook();
         result = 37 * result + ( getBorrowedDate() == null ? 0 : this.getBorrowedDate().hashCode() );
         return result;
   }   


}


