package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Librarian generated by hbm2java
 */
public class Librarian  implements java.io.Serializable {


     private int idLibrarian;
     private Account account;
     private String name;
     private Date birthday;
     private String gender;
     private String phone;
     private String address;

    public Librarian() {
    }

	
    public Librarian(int idLibrarian, Account account, String name, Date birthday, String gender) {
        this.idLibrarian = idLibrarian;
        this.account = account;
        this.name = name;
        this.birthday = birthday;
        this.gender = gender;
    }
    public Librarian(int idLibrarian, Account account, String name, Date birthday, String gender, String phone, String address) {
       this.idLibrarian = idLibrarian;
       this.account = account;
       this.name = name;
       this.birthday = birthday;
       this.gender = gender;
       this.phone = phone;
       this.address = address;
    }
   
    public int getIdLibrarian() {
        return this.idLibrarian;
    }
    
    public void setIdLibrarian(int idLibrarian) {
        this.idLibrarian = idLibrarian;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


