package Entities;
// Generated Aug 14, 2020 10:23:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reader generated by hbm2java
 */
public class Reader  implements java.io.Serializable {


     private int idReader;
     private String name;
     private Date birthday;
     private String gender;
     private String type;
     private String unit;
     private String phone;
     private byte isExpired;
     private byte isBlocked;
     private Date createTime;
     private Date lastMortifiedTime;
     private Set borrowedBooks = new HashSet(0);

    public Reader() {
    }

	
    public Reader(int idReader, String name, Date birthday, String gender, String type, String unit, byte isExpired, byte isBlocked, Date createTime, Date lastMortifiedTime) {
        this.idReader = idReader;
        this.name = name;
        this.birthday = birthday;
        this.gender = gender;
        this.type = type;
        this.unit = unit;
        this.isExpired = isExpired;
        this.isBlocked = isBlocked;
        this.createTime = createTime;
        this.lastMortifiedTime = lastMortifiedTime;
    }
    public Reader(int idReader, String name, Date birthday, String gender, String type, String unit, String phone, byte isExpired, byte isBlocked, Date createTime, Date lastMortifiedTime, Set borrowedBooks) {
       this.idReader = idReader;
       this.name = name;
       this.birthday = birthday;
       this.gender = gender;
       this.type = type;
       this.unit = unit;
       this.phone = phone;
       this.isExpired = isExpired;
       this.isBlocked = isBlocked;
       this.createTime = createTime;
       this.lastMortifiedTime = lastMortifiedTime;
       this.borrowedBooks = borrowedBooks;
    }
   
    public int getIdReader() {
        return this.idReader;
    }
    
    public void setIdReader(int idReader) {
        this.idReader = idReader;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public byte getIsExpired() {
        return this.isExpired;
    }
    
    public void setIsExpired(byte isExpired) {
        this.isExpired = isExpired;
    }
    public byte getIsBlocked() {
        return this.isBlocked;
    }
    
    public void setIsBlocked(byte isBlocked) {
        this.isBlocked = isBlocked;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getLastMortifiedTime() {
        return this.lastMortifiedTime;
    }
    
    public void setLastMortifiedTime(Date lastMortifiedTime) {
        this.lastMortifiedTime = lastMortifiedTime;
    }
    public Set getBorrowedBooks() {
        return this.borrowedBooks;
    }
    
    public void setBorrowedBooks(Set borrowedBooks) {
        this.borrowedBooks = borrowedBooks;
    }




}


