/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.General;

/**
 *
 * @author Yukino
 */
public class LibraryRuleJFrame extends javax.swing.JFrame {
    
    public LibraryRuleJFrame() {
        initComponents();
        ruleTextArea.setLineWrap(true);
        ruleTextArea.setWrapStyleWord(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ruleTextArea = new javax.swing.JTextArea();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NỘI QUY THƯ VIỆN");

        ruleTextArea.setBackground(new java.awt.Color(240, 240, 240));
        ruleTextArea.setColumns(20);
        ruleTextArea.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ruleTextArea.setRows(5);
        ruleTextArea.setText("VỀ VIỆC ĐỌC SÁCH\nYêu cầu bạn đọc đến thư viện không mang theo đồ ăn, nước uống.\nĐọc sách xong để lại giá sách hoặc bàn để sách.\nTrong phòng đọc vui lòng giữ trật tự để không làm ồn đến người xung quanh\n\nVỀ VIỆC MƯỢN SÁCH\nBạn đọc phải có thẻ thành viên mới được mượn sách. Vui lòng xuất trình thẻ trước khi mượn sách.\nTối đa mỗi người được mượn 5 quyển sách.\nThời gian mượn sách là 03 tuần và được gia hạn thêm 01 tuần.\nQuá thời gian mượn sách, sẽ bị phạt 1000 vnđ/1 cuốn/ 1 ngày\n\nVỀ VIỆC MẤT SÁCH, HƯ HỎNG\nMọi trường hợp sách bị mất mát, hư hỏng (rách, mất trang, dính bẩn, ẩm ướt,...) đều phải đền bù: giá bìa sách cộng thêm tiền xử lý tem, phân loại, nhãn (50.000 đ/cuốn);\n\nVỀ QUY ĐỊNH THẺ NGƯỜI ĐỌC\nSau khi kết thúc năm học, tất cả thẻ sẽ hết hạn. Nếu năm học mới người đọc có nhu cầu mở lại thẻ vui lòng đến thư viện để gia hạn thẻ.\n");
        ruleTextArea.setToolTipText("");
        jScrollPane1.setViewportView(ruleTextArea);

        homeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeButton.setText("Trang chủ");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(homeButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new HomeFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ruleTextArea;
    // End of variables declaration//GEN-END:variables
}
