/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Librarian;

import Entities.Account;
import Entities.Librarian;
import View.General.HomeFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yukino
 */
public class MainLibrarian extends javax.swing.JFrame {

    private Account librarian = new Account();
    //private Librarian librarian = new Librarian();
            
    public MainLibrarian() {
        initComponents();

    }
    
    public MainLibrarian(Account iLibrarian) {
        initComponents();
        librarian.copyAccount(iLibrarian);
        librarianLabel.setText(librarian.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPopupMenu = new javax.swing.JPopupMenu();
        logoutItem_ad = new javax.swing.JMenuItem();
        headerPanel = new javax.swing.JPanel();
        adminHomeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        librarianLabel = new javax.swing.JLabel();
        mainDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addBorrowedBook = new javax.swing.JMenuItem();
        returnBook = new javax.swing.JMenuItem();
        extension = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        creatReaderCard = new javax.swing.JMenuItem();
        readerList = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        overDuaBookList = new javax.swing.JMenuItem();

        adminPopupMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        logoutItem_ad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutItem_ad.setText("Đăng xuất");
        logoutItem_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItem_adActionPerformed(evt);
            }
        });
        adminPopupMenu.add(logoutItem_ad);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminHomeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        adminHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminHomeLabel.setText("THỦ THƯ");
        adminHomeLabel.setToolTipText("");

        librarianLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        librarianLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        librarianLabel.setText("username");
        librarianLabel.setToolTipText("");
        librarianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminHomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(librarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainDesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        mainDesktopPane.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Quản lý mượn sách");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        addBorrowedBook.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addBorrowedBook.setText("Thêm sách mượn");
        addBorrowedBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBorrowedBookActionPerformed(evt);
            }
        });
        jMenu1.add(addBorrowedBook);

        returnBook.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        returnBook.setText("Trả sách");
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        jMenu1.add(returnBook);

        extension.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        extension.setText("Gia hạn mượn sách");
        extension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extensionActionPerformed(evt);
            }
        });
        jMenu1.add(extension);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý người đọc");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        creatReaderCard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        creatReaderCard.setText("Thêm mới thẻ người đọc");
        creatReaderCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatReaderCardActionPerformed(evt);
            }
        });
        jMenu2.add(creatReaderCard);

        readerList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        readerList.setText("Danh sách người đọc");
        readerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerListActionPerformed(evt);
            }
        });
        jMenu2.add(readerList);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sách quá hạn");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        overDuaBookList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        overDuaBookList.setText("Danh sách sách quá hạn");
        overDuaBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overDuaBookListActionPerformed(evt);
            }
        });
        jMenu3.add(overDuaBookList);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainDesktopPane)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBorrowedBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBorrowedBookActionPerformed
        BorrowBookInternalFrame f = new BorrowBookInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_addBorrowedBookActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        ReturnBookInternalFrame f = new ReturnBookInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_returnBookActionPerformed

    private void extensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extensionActionPerformed
        ExtensionInternalFrame f = new ExtensionInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_extensionActionPerformed

    private void creatReaderCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatReaderCardActionPerformed
        CreateNewReaderInternalFrame f = new CreateNewReaderInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_creatReaderCardActionPerformed

    private void readerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerListActionPerformed
        ReaderListInternalFrame f = new ReaderListInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_readerListActionPerformed

    private void overDuaBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overDuaBookListActionPerformed
        OverDueBookListInternalFrame f = new OverDueBookListInternalFrame();
        f.setVisible(true);
        this.mainDesktopPane.add(f);
    }//GEN-LAST:event_overDuaBookListActionPerformed

    private void librarianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianLabelMouseClicked
        adminPopupMenu.show(librarianLabel, evt.getX()-20, evt.getY()+10);
    }//GEN-LAST:event_librarianLabelMouseClicked

    private void logoutItem_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItem_adActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất","Đăng xuất",JOptionPane.YES_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new HomeFrame().setVisible(true);
        }
    }//GEN-LAST:event_logoutItem_adActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLibrarian(new Account(2, "librarian1", "e10adc3949ba59abbe56e057f20f883e", "librarian")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBorrowedBook;
    private javax.swing.JLabel adminHomeLabel;
    private javax.swing.JPopupMenu adminPopupMenu;
    private javax.swing.JMenuItem creatReaderCard;
    private javax.swing.JMenuItem extension;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel librarianLabel;
    private javax.swing.JMenuItem logoutItem_ad;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenuItem overDuaBookList;
    private javax.swing.JMenuItem readerList;
    private javax.swing.JMenuItem returnBook;
    // End of variables declaration//GEN-END:variables
}
